apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: spring-boot
spec:
  selector:
    app: myapp
    version: v1
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      name: web
      targetPort: 30500
      nodePort: 30500

